CREATE SEQUENCE ALUNO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;


CREATE TABLE TBL_ALUNO (
    cd_aluno INTEGER DEFAULT ALUNO_SEQ.NEXTVAL NOT NULL,
    nm_aluno VARCHAR2(255) NOT NULL,
    data_nascimento DATE NOT NULL,
    nr_rm VARCHAR2(20) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    telefone VARCHAR2(11) NOT NULL
); 